name: termlib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  ffi: ^2.1.0
  meta: ^1.11.0
  termansi:
    path: ../termansi
  termparser:
    path: ../termparser
  win32: ^5.1.1
  # path: ^1.8.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
